<?php

return [
    // รายชื่อรหัสแพทย์เป้าหมาย (EKG-ECHO)
    'target_doctors' => [
        ' 21116',
        ' 22947',
        ' 26587',
        ' 33166',
        ' 34559',
        ' 37288',
        ' 36155',
        ' 34916'
    ],

    // รหัสแผนกที่ยกเลิก
    'excluded_dept_descriptions' => [
        'ยกเลิก',
        '(ยกเลิก) พัฒนาการเด็ก',
        '(ยกเลิก) คลินิกโรคเลือดในเด็ก',
        '(ยกเลิก)คลินิกนมแม่',
    ],

    // รหัสวอร์ดที่ยกเว้น (ไม่แสดงใน dropdown)
    'excluded_ward_ids' => [
        'IQF01',
        'IQF02',
        'IQF03',
        'IQF04',
        'IQF05',
        'IQF06',
        'IQF07',
        'IQF08',
        'IQF09',
        'IQF10',
        'IQF11',
        'IQF12',
        'IQF13',
        'IQF14',
        'IQF15',
        'IQF16',
        'IQF17',
        'IQF18',
        'IQM01',
        'IQM02',
        'IQM03',
        'IQM04',
        'IQM05',
        'IQM06',
        'IQM07',
        'IQM08',
        'IQM09',
        'IQM10',
        'IQM11',
        'IQM12',
        'IQM13',
        'IQM14',
        'IQM15',
        'IQM16',
        'IQM17',
        'IQM18',
        'IQM19',
        'IQM20',
        'IQM21',
        'IQM22',
        'IQM23',
        'IQM24',
        'IQM25',
        'IQM26',
        'IQM27',
        'IQW',
        'IQWF8',
        'IQWF7',
        'IQWF6',
        'IQWM8',
        'IQWM7',
        'IQWM6',
        'IQWM5',
        'IQWM4',
        'IQWM3',
        'IQWM2',
        'IQWM1'
    ],
];
